[[CUDAFastRegistrationLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29d6a3087761866478e324160fd4d06f117edae1"
libc = "glibc"
os = "linux"

    [[CUDAFastRegistrationLib.download]]
    sha256 = "395cfc0204f76d7779fecaebe5f7ecbaac2f3303421021e673e424030065243b"
    url = "https://github.com/gzhang8/CUDAFastRegistrationLib_jll.jl/releases/download/CUDAFastRegistrationLib-v0.1.0+0/CUDAFastRegistrationLib.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CUDAFastRegistrationLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e6d7c60acbe8a4f7ecdd5c072edb76e56fb2c88"
libc = "glibc"
os = "linux"

    [[CUDAFastRegistrationLib.download]]
    sha256 = "bfecbcff412b24397fdf1d5c7417337392a88874a1f6627b0f533be1f3cf586b"
    url = "https://github.com/gzhang8/CUDAFastRegistrationLib_jll.jl/releases/download/CUDAFastRegistrationLib-v0.1.0+0/CUDAFastRegistrationLib.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
